/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.ngo.manager;

import business.organization.logistics.LogisticsManagerOrganization;
import business.util.request.RequestItem;
import business.util.request.RequestStatus;
import business.workQueue.CollectionWorkRequest;
import business.workQueue.ShortageWorkRequest;
import business.workQueue.WorkRequest;
import business.enterprise.Enterprise;
import business.network.Network;
import business.organization.Organization;
import business.role.Role;
import business.userAccount.UserAccount;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 *
 * @author Shubham Idekar
 */
public class NGOOtherRegionsRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Network network;
    private CollectionWorkRequest collectionWorkRequest;
    private String message;

    /**
     * Creates new form NGOOtherRegionsRequestJPanel
     */
    public NGOOtherRegionsRequestJPanel(JPanel userProcessContainer, CollectionWorkRequest collectionWorkRequest, Organization organization, UserAccount account, Network network, String message) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.collectionWorkRequest = collectionWorkRequest;
        this.account = account;
        this.organization = organization;
        this.network = network;
        this.message = message;

        populateShortageTable();
        populateRequestDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        tblShortage = new javax.swing.JTable();
        jSeparator = new javax.swing.JSeparator();
        btnAssign = new javax.swing.JButton();
        lblQuantity = new javax.swing.JLabel();
        lblRequestStatusVal = new javax.swing.JLabel();
        lblRequestStatus = new javax.swing.JLabel();
        lblRequestDateVal = new javax.swing.JLabel();
        lblRequestDate = new javax.swing.JLabel();
        lblRequestFromVal = new javax.swing.JLabel();
        lblRequestFrom = new javax.swing.JLabel();
        jScrollPaneRequestDetails = new javax.swing.JScrollPane();
        tblRequestDetails = new javax.swing.JTable();
        lblQuantityVal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 153));

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Redirect Request");

        tblShortage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "NGO Name", "Raised By(Manager Name)", "Assign to Employee", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(tblShortage);
        if (tblShortage.getColumnModel().getColumnCount() > 0) {
            tblShortage.getColumnModel().getColumn(0).setResizable(false);
            tblShortage.getColumnModel().getColumn(1).setResizable(false);
            tblShortage.getColumnModel().getColumn(2).setResizable(false);
            tblShortage.getColumnModel().getColumn(3).setResizable(false);
            tblShortage.getColumnModel().getColumn(4).setResizable(false);
        }

        btnAssign.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        lblQuantity.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblQuantity.setText("Food Quantity:");

        lblRequestStatusVal.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblRequestStatusVal.setText("<request_status>");

        lblRequestStatus.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblRequestStatus.setText("Request status:");

        lblRequestDateVal.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblRequestDateVal.setText("<request_date>");

        lblRequestDate.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblRequestDate.setText("Request Date:");

        lblRequestFromVal.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblRequestFromVal.setText("<request_from>");

        lblRequestFrom.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblRequestFrom.setText("Request from:");

        tblRequestDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantity", "Type", "Hours to perish"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneRequestDetails.setViewportView(tblRequestDetails);

        lblQuantityVal.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 12)); // NOI18N
        lblQuantityVal.setText("<quantity>");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/ngo/manager/res/forwarding.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/ngo/manager/res/share.png"))); // NOI18N

        btnBack1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(51, 51, 255));
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/res/back-button.png"))); // NOI18N
        btnBack1.setText("Back");
        btnBack1.setBorder(null);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRequestFrom)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblQuantity)
                                            .addComponent(lblRequestStatus))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblQuantityVal)
                                            .addComponent(lblRequestDateVal)
                                            .addComponent(lblRequestStatusVal)
                                            .addComponent(lblRequestFromVal)))
                                    .addComponent(lblRequestDate))
                                .addGap(371, 371, 371)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPaneRequestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)))
                .addGap(0, 490, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRequestFrom)
                            .addComponent(lblRequestFromVal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRequestDate)
                            .addComponent(lblRequestDateVal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRequestStatus)
                            .addComponent(lblRequestStatusVal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(lblQuantityVal))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addComponent(jScrollPaneRequestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed

        int selectedRow = tblShortage.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,
                    "Please select a shortage request",
                    "Information",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        ShortageWorkRequest swr = (ShortageWorkRequest) tblShortage.getValueAt(selectedRow, 4);

        collectionWorkRequest.setDeliverTo(swr.getAssignToEmployee());
        collectionWorkRequest.setDeliverToNGO(swr.getNgoName());
        collectionWorkRequest.setMessage(message);
        collectionWorkRequest.setStatus(RequestStatus.getPickupStatusMessage(2));
        swr.setLinkedCollectionWorkRequest(collectionWorkRequest);
        swr.setStatus(RequestStatus.getShortageStatusMessage(2));

        // Adding to own queue
        account.getWorkQueue().getWorkRequestList().add(collectionWorkRequest);

        // Adding to Logistics Manager Organization queue
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                if (o instanceof LogisticsManagerOrganization) {
                    o.getWorkQueue().getWorkRequestList().add(collectionWorkRequest);
                    break;
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Request sucessfully redirected to another NGO.", "Information", JOptionPane.INFORMATION_MESSAGE);
        btnAssign.setEnabled(false);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void populateShortageTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblShortage.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr.getStatus().equals(RequestStatus.getShortageStatusMessage(1))) {
                if (wr instanceof ShortageWorkRequest) {
                    ShortageWorkRequest swr = (ShortageWorkRequest) wr;

                    Object row[] = new Object[5];
                    row[0] = swr.getRequestDate();
                    row[1] = swr.getSender().getEmployee().getName();
                    row[2] = swr.getNgoName();
                    row[3] = swr.getAssignToEmployee();
                    row[4] = swr;

                    dtm.addRow(row);
                }
            }
        }
    }

    public void populateRequestDetails() {
        String status = collectionWorkRequest.getStatus();

        lblRequestStatusVal.setText(status);
        lblRequestFromVal.setText(collectionWorkRequest.getRaisedByRestaurant());
        lblRequestDateVal.setText(collectionWorkRequest.getRequestDate() + "");
        lblQuantityVal.setText(collectionWorkRequest.getTotalQuantity() + " pounds");

        populateTable();
    }

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblRequestDetails.getModel();
        dtm.setRowCount(0);

        for (RequestItem ri : collectionWorkRequest.getRequestItems()) {
            if (ri.getQuantity() > 0) {
                Object row[] = new Object[3];
                row[0] = ri;
                row[1] = ri.getQuantity();
                row[2] = ri.getHoursToPerish();

                dtm.addRow(row);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPaneRequestDetails;
    private javax.swing.JSeparator jSeparator;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblQuantityVal;
    private javax.swing.JLabel lblRequestDate;
    private javax.swing.JLabel lblRequestDateVal;
    private javax.swing.JLabel lblRequestFrom;
    private javax.swing.JLabel lblRequestFromVal;
    private javax.swing.JLabel lblRequestStatus;
    private javax.swing.JLabel lblRequestStatusVal;
    private javax.swing.JTable tblRequestDetails;
    private javax.swing.JTable tblShortage;
    // End of variables declaration//GEN-END:variables
}
