/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation.logistics.manager;

import business.userAccount.UserAccount;
import business.workQueue.PaymentWorkRequest;
import business.workQueue.WorkRequest;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author mites
 */
public class ManagerViewChartJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;

    /**
     * Creates new form LogisticsManagerViewChartJPanel
     */
    public ManagerViewChartJPanel(JPanel userProcessContainer, UserAccount account) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        populateChart();
    }

    public void populateChart() {

        DefaultPieDataset dataSet = new DefaultPieDataset();
        int paid = 0, unpaid = 0;
        double paidAmount = 0, unpaidAmount = 0;

        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof PaymentWorkRequest) {
                PaymentWorkRequest pwr = (PaymentWorkRequest) wr;
                if (pwr.getCollectionWorkRequest().getInvoiceGenerated()) {
                    if (pwr.getCollectionWorkRequest().getPaid()) {
                        paid++;
                        paidAmount += pwr.getCollectionWorkRequest().getDeliveryCost();
                    } else {
                        unpaid++;
                        unpaidAmount += pwr.getCollectionWorkRequest().getDeliveryCost();
                    }
                }
            }
        }

        dataSet.setValue("Paid", paid);
        dataSet.setValue("Unpaid", unpaid);

        JFreeChart chart = ChartFactory.createPieChart("Paid and Unpaid Invoices",
                dataSet, true, true, true);

        PiePlot plot = (PiePlot) chart.getPlot();

        ChartPanel chartPanel = new ChartPanel(chart);
        pnlChart.removeAll();
        pnlChart.add(chartPanel, BorderLayout.CENTER);
        pnlChart.validate();

        lblPaidVal.setText("$ " + paidAmount);
        lblUnPaidVal.setText("$ " + unpaidAmount);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChart = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblPaid = new javax.swing.JLabel();
        lblPaidVal = new javax.swing.JLabel();
        lblUnPaid = new javax.swing.JLabel();
        lblUnPaidVal = new javax.swing.JLabel();
        lblHeading = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));

        pnlChart.setBackground(new java.awt.Color(255, 255, 204));
        pnlChart.setLayout(new java.awt.BorderLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentation/res/back-button.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPaid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPaid.setText("Total Amount Received (Paid) :");

        lblPaidVal.setText("<paid>");

        lblUnPaid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUnPaid.setText("Total Amount Pending (Un-Paid) :");

        lblUnPaidVal.setText("<un-paid>");

        lblHeading.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblHeading.setForeground(new java.awt.Color(0, 102, 255));
        lblHeading.setText("View Invoice Payement Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUnPaid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPaidVal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUnPaidVal, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHeading)))
                .addContainerGap(401, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPaidVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUnPaid)
                    .addComponent(lblUnPaidVal))
                .addGap(18, 18, 18)
                .addComponent(pnlChart, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblHeading;
    private javax.swing.JLabel lblPaid;
    private javax.swing.JLabel lblPaidVal;
    private javax.swing.JLabel lblUnPaid;
    private javax.swing.JLabel lblUnPaidVal;
    private javax.swing.JPanel pnlChart;
    // End of variables declaration//GEN-END:variables
}
